name: Publish Package to GitHub NPM Registry

on: 
  workflow_dispatch:
  push:
  release: 
    types: published
    
jobs:
    test-publish-package:
      permissions: 
        packages: write
        contents: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - 20.x
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            registry-url: 'https://npm.pkg.github.com'
            
        - name: Install Dependencies
          run: npm install

        - name: Pulish the Package
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    test:
      runs-on: ubuntu-latest
      services:
        mongodb:
          image: mongo:5
          ports:
            - 27017:27017
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Wait for MongoDB to be ready
          run: |
            echo "Waiting for MongoDB..."
            until nc -z localhost 27017; do
              sleep 2
            done
        - name: Run tests
          run: ./run-tests.sh

